/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pa.p3;

import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Font;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFileChooser;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.filechooser.FileNameExtensionFilter;


/**
 *
 * @author alumno
 */
public class P6 extends javax.swing.JFrame {

    JTextArea textArea;
    /**
     * Creates new form P6
     */
    public P6() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        menuBar2 = new java.awt.MenuBar();
        menu3 = new java.awt.Menu();
        menu4 = new java.awt.Menu();
        popupMenu1 = new java.awt.PopupMenu();
        Close_Button = new javax.swing.JButton();
        AreaTexto = new javax.swing.JMenuBar();
        Menu_File = new javax.swing.JMenu();
        NewButtton = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        OpenButton = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        SaveButton = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        PrintButton = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        Menu_Edit = new javax.swing.JMenu();
        CutButton = new javax.swing.JMenuItem();
        CopyButton = new javax.swing.JMenuItem();
        PasteButton = new javax.swing.JMenuItem();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        menu3.setLabel("File");
        menuBar2.add(menu3);

        menu4.setLabel("Edit");
        menuBar2.add(menu4);

        popupMenu1.setLabel("popupMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Close_Button.setText("Close");
        Close_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Close_ButtonActionPerformed(evt);
            }
        });

        Menu_File.setText("File");

        NewButtton.setText("New");
        NewButtton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewButttonActionPerformed(evt);
            }
        });
        Menu_File.add(NewButtton);
        JTextArea textArea = new JTextArea(100, 200);
        JScrollPane scrollPane = new JScrollPane(textArea);
        textArea.setEditable(true);
        textArea.setFont(new Font("Serif", Font.ITALIC, 16));
        textArea.setLineWrap(true);
        textArea.setWrapStyleWord(true);
        Menu_File.add(jSeparator2);

        OpenButton.setText("Open");
        OpenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenButtonActionPerformed(evt);
            }
        });
        Menu_File.add(OpenButton);
        Menu_File.add(jSeparator3);

        SaveButton.setText("Save");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });
        Menu_File.add(SaveButton);
        Menu_File.add(jSeparator4);

        PrintButton.setText("Print");
        PrintButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintButtonActionPerformed(evt);
            }
        });
        Menu_File.add(PrintButton);
        Menu_File.add(jSeparator1);

        AreaTexto.add(Menu_File);

        Menu_Edit.setText("Edit");
        Menu_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_EditActionPerformed(evt);
            }
        });

        CutButton.setText("Cut");
        CutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CutButtonActionPerformed(evt);
            }
        });
        Menu_Edit.add(CutButton);

        CopyButton.setText("Copy");
        CopyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CopyButtonActionPerformed(evt);
            }
        });
        Menu_Edit.add(CopyButton);

        PasteButton.setText("Paste");
        PasteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasteButtonActionPerformed(evt);
            }
        });
        Menu_Edit.add(PasteButton);

        AreaTexto.add(Menu_Edit);

        setJMenuBar(AreaTexto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Close_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 821, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 385, Short.MAX_VALUE)
                .addComponent(Close_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Close_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Close_ButtonActionPerformed
        JOptionPane.showMessageDialog(null,"Adios, que tenga un buen dia.");
        System.exit(0);
    }//GEN-LAST:event_Close_ButtonActionPerformed

    private void NewButttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewButttonActionPerformed
       
        textArea = new JTextArea();
        textArea.setLineWrap(true);
        textArea.setWrapStyleWord(true);
        textArea.setBounds(52, 76, 360, 156);
        //textArea.setCaretPosition((int) JTextArea.CENTER_ALIGNMENT);
        JScrollPane scroll = new JScrollPane(textArea);
        scroll.setBounds(52, 76, 360, 156);
        AreaTexto.add(scroll);
        
        /*textArea = new JTextArea(50, 100);
        setLayout(new FlowLayout());
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        textArea.setWrapStyleWord(true);
        textArea.setLineWrap(true);
        add(textArea);
        setSize(100, 100);
        setLocationRelativeTo(this);
        setVisible(true);
        textArea.setWrapStyleWord(true);
        textArea.setLineWrap(true);*/

    }//GEN-LAST:event_NewButttonActionPerformed

    private void CutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CutButtonActionPerformed
       textArea.cut();
    }//GEN-LAST:event_CutButtonActionPerformed

    private void OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenActionPerformed
        
    }//GEN-LAST:event_OpenActionPerformed

    private void Menu_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_EditActionPerformed
    }//GEN-LAST:event_Menu_EditActionPerformed

    private void PasteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasteButtonActionPerformed
        textArea.paste();
    }//GEN-LAST:event_PasteButtonActionPerformed

    private void CopyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CopyButtonActionPerformed
        textArea.copy();
    }//GEN-LAST:event_CopyButtonActionPerformed

    private void PrintButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintButtonActionPerformed

        //textArea.append("\n"); 
        //textArea.append(textArea.getText()); 
        System.out.println(textArea.getText());
    }//GEN-LAST:event_PrintButtonActionPerformed

    private void OpenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenButtonActionPerformed
        
        //Creamos el objeto JFileChooser
        JFileChooser fileChooser = new JFileChooser();
        
        //Indicamos que podemos seleccionar varios ficheros
        fileChooser.setMultiSelectionEnabled(true);
        
        //Indicamos lo que podemos seleccionar
        fileChooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
                
        //Creamos el filtro
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("*.TXT", "txt");
        fileChooser.setFileFilter(filtro);
        
        if(fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION){
            
            File[] ficheros = fileChooser.getSelectedFiles();
            
            for(int i = 0; i < ficheros.length; ++i){
                try(BufferedReader br = new BufferedReader(new FileReader(ficheros[i]))){
                    String linea = br.readLine();
                    textArea.append(linea + "\n");
                } catch (IOException e1) {
                    JOptionPane.showMessageDialog(null, "Ha ocurrido un error al intentar abiri el fichero " + ficheros[i].getName());
                }
                JOptionPane.showMessageDialog(null, "Fichero " + ficheros[i].getName() + " abierto correctamente");
            }
            
            /*textArea = new JTextArea(50, 100);
            setLayout(new FlowLayout());
            setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            add(textArea);
            setSize(200, 200);
            setLocationRelativeTo(this);
            setVisible(true);*/
       
        }     
    }//GEN-LAST:event_OpenButtonActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        int seleccion = fileChooser.showSaveDialog(this);
        if (seleccion == JFileChooser.APPROVE_OPTION){
            File fichero = fileChooser.getSelectedFile();
            try (
                FileWriter f = new FileWriter(fichero);      
            ){
                f.write(textArea.getText() + "\n");
            }catch (IOException ex) {
                Logger.getLogger(P6.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_SaveButtonActionPerformed
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(P6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(P6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(P6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(P6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new P6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar AreaTexto;
    private javax.swing.JButton Close_Button;
    private javax.swing.JMenuItem CopyButton;
    private javax.swing.JMenuItem CutButton;
    private javax.swing.JMenu Menu_Edit;
    private javax.swing.JMenu Menu_File;
    public javax.swing.JMenuItem NewButtton;
    private javax.swing.JMenuItem OpenButton;
    private javax.swing.JMenuItem PasteButton;
    private javax.swing.JMenuItem PrintButton;
    private javax.swing.JMenuItem SaveButton;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.Menu menu3;
    private java.awt.Menu menu4;
    private java.awt.MenuBar menuBar1;
    private java.awt.MenuBar menuBar2;
    private java.awt.PopupMenu popupMenu1;
    // End of variables declaration//GEN-END:variables
}
